### ISSUE TITLE
Faltantes

### ISSUE THREAD

**Issue by Jparrgam** [gforeroh/prueba-laravel#1]
por favor arreglar y terminar la prueba que se envió.

`dd("jajajaja"); die;`

` // $user = Auth::user();
        // dd("Mama");
        // dd($user); 
        // die;`

**Comment by gforeroh** [comment]
Se realizaron las respectivas correcciones.

Link de Github 
https://github.com/gforeroh/prueba-laravel.git

git clone https://github.com/gforeroh/prueba-laravel.git
composer install
npm install

Configurar Archivo .env (Acceso base de datos)

php artisan key:generate
php artisan config:cache

base datos: "php artisan migrate"

php artisan db:seed --class=UsersTableSeeder

inicio proyecto 
"php artisan serve"
"npm run production"

Usuario: admin@test.com
Password: 123456789
